//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NautilusGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryFoto
    {
        public int Id { get; set; }
        public int Id_Album { get; set; }
        public string PathImage { get; set; }
    }
}
